
// Complete Moves Database from PokemonDB.net
var movesDatabase = {
    "Pound": { power: 32, accuracy: 100, pp: 35, type: "Normal", category: "Physical", effect: "None" },
    "Karate Chop": { power: 40, accuracy: 100, pp: 25, type: "Fighting", category: "Physical", effect: "High critical hit ratio" },
    "Double Slap": { power: 12, accuracy: 85, pp: 10, type: "Normal", category: "Physical", effect: "Hits 2-5 times" },
    "Comet Punch": { power: 14, accuracy: 85, pp: 15, type: "Normal", category: "Physical", effect: "Hits 2-5 times" },
    "Mega Punch": { power: 64, accuracy: 85, pp: 20, type: "Normal", category: "Physical", effect: "None" },
    "Pay Day": { power: 32, accuracy: 100, pp: 20, type: "Normal", category: "Physical", effect: "Scatters money" },
    "Fire Punch": { power: 60, accuracy: 100, pp: 15, type: "Fire", category: "Physical", effect: "May burn" },
    "Ice Punch": { power: 60, accuracy: 100, pp: 15, type: "Ice", category: "Physical", effect: "May freeze" },
    "Thunder Punch": { power: 60, accuracy: 100, pp: 15, type: "Electric", category: "Physical", effect: "May paralyze" },
    "Scratch": { power: 32, accuracy: 100, pp: 35, type: "Normal", category: "Physical", effect: "None" },
    "Vice Grip": { power: 44, accuracy: 100, pp: 30, type: "Normal", category: "Physical", effect: "None" },
    "Guillotine": { power: 0, accuracy: 30, pp: 5, type: "Normal", category: "Physical", effect: "One-hit KO" },
    "Razor Wind": { power: 64, accuracy: 100, pp: 10, type: "Normal", category: "Special", effect: "High critical hit ratio" },
    "Swords Dance": { power: 0, accuracy: 0, pp: 20, type: "Normal", category: "Status", effect: "Raises Attack by 2 stages" },
    "Cut": { power: 40, accuracy: 95, pp: 30, type: "Normal", category: "Physical", effect: "None" },
    "Gust": { power: 32, accuracy: 100, pp: 35, type: "Flying", category: "Special", effect: "None" },
    "Wing Attack": { power: 48, accuracy: 100, pp: 35, type: "Flying", category: "Physical", effect: "None" },
    "Fly": { power: 72, accuracy: 95, pp: 15, type: "Flying", category: "Physical", effect: "Flies up on first turn" },
    "Bind": { power: 12, accuracy: 85, pp: 20, type: "Normal", category: "Physical", effect: "Traps opponent for 2-5 turns" },
    "Slam": { power: 64, accuracy: 75, pp: 20, type: "Normal", category: "Physical", effect: "None" },
    "Vine Whip": { power: 36, accuracy: 100, pp: 25, type: "Grass", category: "Physical", effect: "None" },
    "Stomp": { power: 52, accuracy: 100, pp: 20, type: "Normal", category: "Physical", effect: "May cause flinch" },
    "Double Kick": { power: 24, accuracy: 100, pp: 30, type: "Fighting", category: "Physical", effect: "Hits twice" },
    "Mega Kick": { power: 96, accuracy: 75, pp: 5, type: "Normal", category: "Physical", effect: "None" },
    "Jump Kick": { power: 80, accuracy: 95, pp: 10, type: "Fighting", category: "Physical", effect: "User takes damage if it misses" },
    "Rolling Kick": { power: 48, accuracy: 85, pp: 15, type: "Fighting", category: "Physical", effect: "May cause flinch" },
    "Sand Attack": { power: 0, accuracy: 100, pp: 15, type: "Ground", category: "Status", effect: "Lowers accuracy by 1 stage" },
    "Headbutt": { power: 56, accuracy: 100, pp: 15, type: "Normal", category: "Physical", effect: "May cause flinch" },
    "Horn Attack": { power: 52, accuracy: 100, pp: 25, type: "Normal", category: "Physical", effect: "None" },
    "Fury Attack": { power: 12, accuracy: 85, pp: 20, type: "Normal", category: "Physical", effect: "Hits 2-5 times" },
    "Horn Drill": { power: 0, accuracy: 30, pp: 5, type: "Normal", category: "Physical", effect: "One-hit KO" },
    "Tackle": { power: 32, accuracy: 100, pp: 35, type: "Normal", category: "Physical", effect: "None" },
    "Body Slam": { power: 68, accuracy: 100, pp: 15, type: "Normal", category: "Physical", effect: "May paralyze" },
    "Wrap": { power: 12, accuracy: 90, pp: 20, type: "Normal", category: "Physical", effect: "Traps opponent for 2-5 turns" },
    "Take Down": { power: 72, accuracy: 85, pp: 20, type: "Normal", category: "Physical", effect: "User takes recoil damage" },
    "Thrash": { power: 96, accuracy: 100, pp: 10, type: "Normal", category: "Physical", effect: "User becomes confused" },
    "Double-Edge": { power: 96, accuracy: 100, pp: 15, type: "Normal", category: "Physical", effect: "User takes recoil damage" },
    "Tail Whip": { power: 0, accuracy: 100, pp: 30, type: "Normal", category: "Status", effect: "Lowers Defense by 1 stage" },
    "Poison Sting": { power: 12, accuracy: 100, pp: 35, type: "Poison", category: "Physical", effect: "May poison" },
    "Twineedle": { power: 20, accuracy: 100, pp: 20, type: "Bug", category: "Physical", effect: "Hits twice, may poison" },
    "Pin Missile": { power: 20, accuracy: 95, pp: 20, type: "Bug", category: "Physical", effect: "Hits 2-5 times" },
    "Leer": { power: 0, accuracy: 100, pp: 30, type: "Normal", category: "Status", effect: "Lowers Defense by 1 stage" },
    "Bite": { power: 48, accuracy: 100, pp: 25, type: "Dark", category: "Physical", effect: "May cause flinch" },
    "Growl": { power: 0, accuracy: 100, pp: 40, type: "Normal", category: "Status", effect: "Lowers Attack by 1 stage" },

    "Sing": { power: 0, accuracy: 55, pp: 15, type: "Normal", category: "Status", effect: "Puts opponent to sleep" },
    "Supersonic": { power: 0, accuracy: 55, pp: 20, type: "Normal", category: "Status", effect: "Confuses opponent" },
    "Sonic Boom": { power: 0, accuracy: 90, pp: 20, type: "Normal", category: "Special", effect: "Always deals 20 damage" },
    "Disable": { power: 0, accuracy: 100, pp: 20, type: "Normal", category: "Status", effect: "Disables last used move" },
    "Acid": { power: 32, accuracy: 100, pp: 30, type: "Poison", category: "Special", effect: "May lower Special Defense" },
    "Ember": { power: 32, accuracy: 100, pp: 25, type: "Fire", category: "Special", effect: "May burn" },
    "Flamethrower": { power: 72, accuracy: 100, pp: 15, type: "Fire", category: "Special", effect: "May burn" },
    "Mist": { power: 0, accuracy: 0, pp: 30, type: "Ice", category: "Status", effect: "Prevents stat reduction" },
    "Water Gun": { power: 32, accuracy: 100, pp: 25, type: "Water", category: "Special", effect: "None" },
    "Hydro Pump": { power: 88, accuracy: 80, pp: 5, type: "Water", category: "Special", effect: "None" },
    "Surf": { power: 72, accuracy: 100, pp: 15, type: "Water", category: "Special", effect: "None" },
    "Ice Beam": { power: 72, accuracy: 100, pp: 10, type: "Ice", category: "Special", effect: "May freeze" },
    "Blizzard": { power: 88, accuracy: 70, pp: 5, type: "Ice", category: "Special", effect: "May freeze" },
    "Psybeam": { power: 52, accuracy: 100, pp: 20, type: "Psychic", category: "Special", effect: "May confuse" },
    "Bubble Beam": { power: 52, accuracy: 100, pp: 20, type: "Water", category: "Special", effect: "May lower Speed" },
    "Aurora Beam": { power: 52, accuracy: 100, pp: 20, type: "Ice", category: "Special", effect: "May lower Attack" },
    "Hyper Beam": { power: 120, accuracy: 90, pp: 5, type: "Normal", category: "Special", effect: "User must recharge" },
    "Peck": { power: 28, accuracy: 100, pp: 35, type: "Flying", category: "Physical", effect: "None" },
    "Drill Peck": { power: 64, accuracy: 100, pp: 20, type: "Flying", category: "Physical", effect: "None" },
    "Submission": { power: 64, accuracy: 80, pp: 20, type: "Fighting", category: "Physical", effect: "User takes recoil damage" },
    "Low Kick": { power: 0, accuracy: 100, pp: 20, type: "Fighting", category: "Physical", effect: "Damage based on opponent's weight" },
    "Counter": { power: 0, accuracy: 100, pp: 20, type: "Fighting", category: "Physical", effect: "Returns double the damage taken" },
    "Seismic Toss": { power: 0, accuracy: 100, pp: 20, type: "Fighting", category: "Physical", effect: "Damage equals user's level" },
    "Strength": { power: 64, accuracy: 100, pp: 15, type: "Normal", category: "Physical", effect: "None" },
    "Absorb": { power: 16, accuracy: 100, pp: 25, type: "Grass", category: "Special", effect: "User recovers half the damage dealt" },
    "Mega Drain": { power: 32, accuracy: 100, pp: 15, type: "Grass", category: "Special", effect: "User recovers half the damage dealt" },
    "Leech Seed": { power: 0, accuracy: 90, pp: 10, type: "Grass", category: "Status", effect: "Drains HP each turn" },
    "Growth": { power: 0, accuracy: 0, pp: 20, type: "Normal", category: "Status", effect: "Raises Special Attack by 1 stage" },
    "Razor Leaf": { power: 44, accuracy: 95, pp: 25, type: "Grass", category: "Physical", effect: "High critical hit ratio" },
    "Solar Beam": { power: 96, accuracy: 100, pp: 10, type: "Grass", category: "Special", effect: "Charges on first turn" },
    "Poison Powder": { power: 0, accuracy: 75, pp: 35, type: "Poison", category: "Status", effect: "Poisons opponent" },
    "Stun Spore": { power: 0, accuracy: 75, pp: 30, type: "Grass", category: "Status", effect: "Paralyzes opponent" },
    "Sleep Powder": { power: 0, accuracy: 75, pp: 15, type: "Grass", category: "Status", effect: "Puts opponent to sleep" },
    "Petal Dance": { power: 96, accuracy: 100, pp: 10, type: "Grass", category: "Special", effect: "User becomes confused" },
    "String Shot": { power: 0, accuracy: 95, pp: 40, type: "Bug", category: "Status", effect: "Lowers Speed by 2 stages" },
    "Dragon Rage": { power: 0, accuracy: 100, pp: 10, type: "Dragon", category: "Special", effect: "Always deals 40 damage" },
    "Fire Spin": { power: 28, accuracy: 85, pp: 15, type: "Fire", category: "Special", effect: "Traps opponent for 2-5 turns" },
    "Thunder Shock": { power: 32, accuracy: 100, pp: 30, type: "Electric", category: "Special", effect: "May paralyze" },
    "Thunderbolt": { power: 72, accuracy: 100, pp: 15, type: "Electric", category: "Special", effect: "May paralyze" },
    "Thunder Wave": { power: 0, accuracy: 90, pp: 20, type: "Electric", category: "Status", effect: "Paralyzes opponent" },
    "Thunder": { power: 88, accuracy: 70, pp: 10, type: "Electric", category: "Special", effect: "May paralyze" },
    "Rock Throw": { power: 40, accuracy: 90, pp: 15, type: "Rock", category: "Physical", effect: "None" },
    "Earthquake": { power: 80, accuracy: 100, pp: 10, type: "Ground", category: "Physical", effect: "None" },
    "Fissure": { power: 0, accuracy: 30, pp: 5, type: "Ground", category: "Physical", effect: "One-hit KO" },
    "Dig": { power: 64, accuracy: 100, pp: 10, type: "Ground", category: "Physical", effect: "Digs underground on first turn" },
    "Toxic": { power: 0, accuracy: 90, pp: 10, type: "Poison", category: "Status", effect: "Badly poisons opponent" },
    "Confusion": { power: 40, accuracy: 100, pp: 25, type: "Psychic", category: "Special", effect: "May confuse" },
    "Psychic": { power: 72, accuracy: 100, pp: 10, type: "Psychic", category: "Special", effect: "May lower Special Defense" },
    "Hypnosis": { power: 0, accuracy: 60, pp: 20, type: "Psychic", category: "Status", effect: "Puts opponent to sleep" },
    "Meditate": { power: 0, accuracy: 0, pp: 40, type: "Psychic", category: "Status", effect: "Raises Attack by 1 stage" },
    "Agility": { power: 0, accuracy: 0, pp: 30, type: "Psychic", category: "Status", effect: "Raises Speed by 2 stages" },
    "Quick Attack": { power: 32, accuracy: 100, pp: 30, type: "Normal", category: "Physical", effect: "Always goes first" },
    "Rage": { power: 16, accuracy: 100, pp: 20, type: "Normal", category: "Physical", effect: "Raises Attack when hit" },
    "Night Shade": { power: 0, accuracy: 100, pp: 15, type: "Ghost", category: "Special", effect: "Damage equals user's level" },
    "Mimic": { power: 0, accuracy: 0, pp: 10, type: "Normal", category: "Status", effect: "Copies opponent's last move" },

    "Double Team": { power: 0, accuracy: 0, pp: 15, type: "Normal", category: "Status", effect: "Raises evasion by 1 stage" },
    "Recover": { power: 0, accuracy: 0, pp: 10, type: "Normal", category: "Status", effect: "Restores half max HP" },
    "Harden": { power: 0, accuracy: 0, pp: 30, type: "Normal", category: "Status", effect: "Raises Defense by 1 stage" },

    "Smokescreen": { power: 0, accuracy: 100, pp: 20, type: "Normal", category: "Status", effect: "Lowers accuracy by 1 stage" },
    "Confuse Ray": { power: 0, accuracy: 100, pp: 10, type: "Ghost", category: "Status", effect: "Confuses opponent" },
    "Defense Curl": { power: 0, accuracy: 0, pp: 40, type: "Normal", category: "Status", effect: "Raises Defense by 1 stage" },
    "Barrier": { power: 0, accuracy: 0, pp: 20, type: "Psychic", category: "Status", effect: "Raises Defense by 2 stages" },
    "Light Screen": { power: 0, accuracy: 0, pp: 30, type: "Psychic", category: "Status", effect: "Reduces Special damage for 5 turns" },
    "Haze": { power: 0, accuracy: 0, pp: 30, type: "Ice", category: "Status", effect: "Resets all stat changes" },
    "Reflect": { power: 0, accuracy: 0, pp: 20, type: "Psychic", category: "Status", effect: "Reduces Physical damage for 5 turns" },
    "Focus Energy": { power: 0, accuracy: 0, pp: 30, type: "Normal", category: "Status", effect: "Raises critical hit ratio" },
    "Bide": { power: 0, accuracy: 0, pp: 10, type: "Normal", category: "Physical", effect: "Waits 2 turns then strikes back" },
    "Metronome": { power: 0, accuracy: 0, pp: 10, type: "Normal", category: "Status", effect: "Uses random move" },
    "Mirror Move": { power: 0, accuracy: 0, pp: 20, type: "Flying", category: "Status", effect: "Uses opponent's last move" },
    "Egg Bomb": { power: 80, accuracy: 75, pp: 10, type: "Normal", category: "Physical", effect: "None" },
    "Lick": { power: 24, accuracy: 100, pp: 30, type: "Ghost", category: "Physical", effect: "May paralyze" },
    "Smog": { power: 24, accuracy: 70, pp: 20, type: "Poison", category: "Special", effect: "May poison" },
    "Sludge": { power: 52, accuracy: 100, pp: 20, type: "Poison", category: "Special", effect: "May poison" },
    "Bone Club": { power: 52, accuracy: 85, pp: 20, type: "Ground", category: "Physical", effect: "May cause flinch" },
    "Fire Blast": { power: 88, accuracy: 85, pp: 5, type: "Fire", category: "Special", effect: "May burn" },
    "Waterfall": { power: 64, accuracy: 100, pp: 15, type: "Water", category: "Physical", effect: "May cause flinch" },
    "Clamp": { power: 28, accuracy: 85, pp: 15, type: "Water", category: "Physical", effect: "Traps opponent for 2-5 turns" },
    "Swift": { power: 48, accuracy: 0, pp: 20, type: "Normal", category: "Special", effect: "Never misses" },
    "Skull Bash": { power: 104, accuracy: 100, pp: 10, type: "Normal", category: "Physical", effect: "Raises Defense on first turn" },
    "Spike Cannon": { power: 16, accuracy: 100, pp: 15, type: "Normal", category: "Physical", effect: "Hits 2-5 times" },
    "Constrict": { power: 8, accuracy: 100, pp: 35, type: "Normal", category: "Physical", effect: "May lower Speed" },
    "Amnesia": { power: 0, accuracy: 0, pp: 20, type: "Psychic", category: "Status", effect: "Raises Special Defense by 2 stages" },
    "Kinesis": { power: 0, accuracy: 80, pp: 15, type: "Psychic", category: "Status", effect: "Lowers accuracy by 1 stage" },
    "Soft-Boiled": { power: 0, accuracy: 0, pp: 10, type: "Normal", category: "Status", effect: "Restores half max HP" },
    "High Jump Kick": { power: 104, accuracy: 90, pp: 10, type: "Fighting", category: "Physical", effect: "User takes damage if it misses" },
    "Glare": { power: 0, accuracy: 100, pp: 30, type: "Normal", category: "Status", effect: "Paralyzes opponent" },
    "Dream Eater": { power: 80, accuracy: 100, pp: 15, type: "Psychic", category: "Special", effect: "Only works on sleeping Pokémon" },
    "Poison Gas": { power: 0, accuracy: 90, pp: 40, type: "Poison", category: "Status", effect: "Poisons opponent" },
    "Barrage": { power: 12, accuracy: 85, pp: 20, type: "Normal", category: "Physical", effect: "Hits 2-5 times" },
    "Leech Life": { power: 16, accuracy: 100, pp: 15, type: "Bug", category: "Physical", effect: "User recovers half the damage dealt" },
    "Lovely Kiss": { power: 0, accuracy: 75, pp: 10, type: "Normal", category: "Status", effect: "Puts opponent to sleep" },
    "Sky Attack": { power: 112, accuracy: 90, pp: 5, type: "Flying", category: "Physical", effect: "Charges on first turn, may cause flinch" },
    "Bubble": { power: 32, accuracy: 100, pp: 30, type: "Water", category: "Special", effect: "May lower Speed" },
    "Dizzy Punch": { power: 56, accuracy: 100, pp: 10, type: "Normal", category: "Physical", effect: "May confuse" },
    "Spore": { power: 0, accuracy: 100, pp: 15, type: "Grass", category: "Status", effect: "Puts opponent to sleep" },
    "Flash": { power: 0, accuracy: 100, pp: 20, type: "Normal", category: "Status", effect: "Lowers accuracy by 1 stage" },
    "Psywave": { power: 0, accuracy: 100, pp: 15, type: "Psychic", category: "Special", effect: "Random damage between 1 and 1.5x user's level" },

    "Acid Armor": { power: 0, accuracy: 0, pp: 20, type: "Poison", category: "Status", effect: "Raises Defense by 2 stages" },
    "Crabhammer": { power: 80, accuracy: 90, pp: 10, type: "Water", category: "Physical", effect: "High critical hit ratio" },
    "Fury Swipes": { power: 14, accuracy: 80, pp: 15, type: "Normal", category: "Physical", effect: "Hits 2-5 times" },
    "Bonemerang": { power: 40, accuracy: 90, pp: 10, type: "Ground", category: "Physical", effect: "Hits twice" },
    "Rest": { power: 0, accuracy: 0, pp: 10, type: "Psychic", category: "Status", effect: "User sleeps for 2 turns and fully recovers" },
    "Rock Slide": { power: 60, accuracy: 90, pp: 10, type: "Rock", category: "Physical", effect: "May cause flinch" },
    "Hyper Fang": { power: 64, accuracy: 90, pp: 15, type: "Normal", category: "Physical", effect: "May cause flinch" },
    "Sharpen": { power: 0, accuracy: 0, pp: 30, type: "Normal", category: "Status", effect: "Raises Attack by 1 stage" },
    "Tri Attack": { power: 64, accuracy: 100, pp: 10, type: "Normal", category: "Special", effect: "May burn, freeze, or paralyze" },
    "Super Fang": { power: 0, accuracy: 90, pp: 10, type: "Normal", category: "Physical", effect: "Reduces opponent's HP to half" },
    "Slash": { power: 56, accuracy: 100, pp: 20, type: "Normal", category: "Physical", effect: "High critical hit ratio" },
    "Struggle": { power: 40, accuracy: 0, pp: 0, type: "Normal", category: "Physical", effect: "User takes recoil damage" },
    "Fire Fang": { power: 52, accuracy: 95, pp: 15, type: "Fire", category: "Physical", effect: "May burn or cause flinch" },
    "Thunder Fang": { power: 52, accuracy: 95, pp: 15, type: "Electric", category: "Physical", effect: "May paralyze or cause flinch" },
    "Ice Fang": { power: 52, accuracy: 95, pp: 15, type: "Ice", category: "Physical", effect: "May freeze or cause flinch" },
    "Dragon Claw": { power: 64, accuracy: 100, pp: 15, type: "Dragon", category: "Physical", effect: "None" },
    "Dragon Rush": { power: 80, accuracy: 75, pp: 10, type: "Dragon", category: "Physical", effect: "May cause flinch" },
    "Shadow Ball": { power: 64, accuracy: 100, pp: 15, type: "Ghost", category: "Special", effect: "May lower Special Defense" },
    "Aura Sphere": { power: 64, accuracy: 0, pp: 20, type: "Fighting", category: "Special", effect: "Never misses" },
    "Calm Mind": { power: 0, accuracy: 0, pp: 20, type: "Psychic", category: "Status", effect: "Raises Special Attack and Special Defense by 1 stage" },
    "Seed Bomb": { power: 64, accuracy: 100, pp: 15, type: "Grass", category: "Physical", effect: "None" },
    "Aqua Tail": { power: 72, accuracy: 90, pp: 10, type: "Water", category: "Physical", effect: "None" },
    "Flame Burst": { power: 56, accuracy: 100, pp: 15, type: "Fire", category: "Special", effect: "May damage adjacent Pokémon" },
    "Water Pulse": { power: 48, accuracy: 100, pp: 20, type: "Water", category: "Special", effect: "May confuse" },
    "Scary Face": { power: 0, accuracy: 100, pp: 10, type: "Normal", category: "Status", effect: "Lowers Speed by 2 stages" },
    "String Shot": { power: 0, accuracy: 95, pp: 40, type: "Bug", category: "Status", effect: "Lowers Speed by 2 stages" },
    "Hypnosis": { power: 0, accuracy: 60, pp: 20, type: "Psychic", category: "Status", effect: "Puts opponent to sleep" },
    "Confusion": { power: 40, accuracy: 100, pp: 25, type: "Psychic", category: "Special", effect: "May confuse" },
    "Fire Spin": { power: 28, accuracy: 85, pp: 15, type: "Fire", category: "Special", effect: "Traps opponent for 2-5 turns" },
    "Double Slap": { power: 12, accuracy: 85, pp: 10, type: "Normal", category: "Physical", effect: "Hits 2-5 times" }
  };